In [1]:
import pandas as pd
import numpy as np

In [71]:
df = pd.read_csv("C:\\Users\\user\\Desktop\\New ML dataset\\energydata_complete.csv")

In [73]:
df.head()

date  Appliances  lights     T1       RH_1    T2       RH_2  \
0  2016-01-11 17:00:00          60      30  19.89  47.596667  19.2  44.790000   
1  2016-01-11 17:10:00          60      30  19.89  46.693333  19.2  44.722500   
2  2016-01-11 17:20:00          50      30  19.89  46.300000  19.2  44.626667   
3  2016-01-11 17:30:00          50      40  19.89  46.066667  19.2  44.590000   
4  2016-01-11 17:40:00          60      40  19.89  46.333333  19.2  44.530000   

      T3       RH_3         T4  ...         T9   RH_9     T_out  Press_mm_hg  \
0  19.79  44.730000  19.000000  ...  17.033333  45.53  6.600000        733.5   
1  19.79  44.790000  19.000000  ...  17.066667  45.56  6.483333        733.6   
2  19.79  44.933333  18.926667  ...  17.000000  45.50  6.366667        733.7   
3  19.79  45.000000  18.890000  ...  17.000000  45.40  6.250000        733.8   
4  19.79  45.000000  18.890000  ...  17.000000  45.40  6.133333        733.9   

   RH_out  Windspeed  Visibility  Tdewpoint        rv1        rv2  
0    92.0   7.000000   63.000000        5.3  13.275433  13.275433  
1    92.0   6.666667   59.166667        5.2  18.606195  18.606195  
2    92.0   6.333333   55.333333        5.1  28.642668  28.642668  
3    92.0   6.000000   51.500000        5.0  45.410389  45.410389  
4    92.0   5.666667   47.666667        4.9  10.084097  10.084097  

[5 rows x 29 columns]

In [74]:
df.drop('date', axis=1, inplace=True)
df.drop('lights', axis=1, inplace=True)

In [75]:
x = df['T2']
y = df['T6']
array = np.array([x])
X = array.reshape(-1,1)

In [76]:
from sklearn.model_selection import cross_validate, train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)


In [77]:
from sklearn.linear_model import LinearRegression


In [78]:
lm = LinearRegression()

In [79]:
lm.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [80]:
predicted_value = lm.predict(X_test)
predicted_value

array([ 2.15578912, 10.01116055,  1.87391554, ...,  4.24758774,
        8.69822311,  4.9893603 ])

In [81]:
from sklearn import metrics

In [41]:
R2 = metrics.r2_score(y_test,predicted_value)
R2
round(R2, 2)

0.64

### Question 13-20


In [42]:
df = pd.read_csv("C:\\Users\\user\\Desktop\\New ML dataset\\energydata_complete.csv")

In [43]:
df.drop('date', axis=1, inplace=True)
df.drop('lights', axis=1, inplace=True)

In [88]:
df.columns

Index(['Appliances', 'T1', 'RH_1', 'T2', 'RH_2', 'T3', 'RH_3', 'T4', 'RH_4',
       'T5', 'RH_5', 'T6', 'RH_6', 'T7', 'RH_7', 'T8', 'RH_8', 'T9', 'RH_9',
       'T_out', 'Press_mm_hg', 'RH_out', 'Windspeed', 'Visibility',
       'Tdewpoint', 'rv1', 'rv2'],
      dtype='object')

In [89]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
normalized_df = pd.DataFrame(scaler.fit_transform(df), columns=df.columns)
feature_df = normalized_df.drop(columns=['Appliances'])
target = normalized_df['Appliances']

In [90]:
from sklearn.model_selection import cross_validate, train_test_split
X_train, X_test, y_train, y_test = train_test_split(feature_df, target, test_size=0.3, random_state=42)

In [91]:
from sklearn.linear_model import LinearRegression
lm =  LinearRegression()

In [92]:
lm.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [93]:
predictions = lm.predict(X_test)
predictions

array([0.03322207, 0.24411599, 0.03400024, ..., 0.06844707, 0.10032325,
       0.05722198])

In [94]:
from sklearn import metrics

In [95]:
MAE=metrics.mean_absolute_error(y_test, predictions)
round(MAE, 2)

0.05

In [96]:
RSS = np.sum(np.square(y_test-predictions))
round(RSS, 2)

45.35

In [97]:
RMSE = np.sqrt(metrics.mean_squared_error(y_test,predictions))
round(RMSE, 3)

0.088

In [98]:
from sklearn.metrics import r2_score
r2_score = r2_score(y_test, predictions)
round(r2_score, 2)

0.15

In [61]:
def get_weights_df(lm, feat, col_name):
  weights = pd.Series(lm.coef_, feat.columns).sort_values()
  weights_df = pd.DataFrame(weights).reset_index()
  weights_df.columns = ['Features', col_name]
  weights_df[col_name].round(3)
  return weights_df

linear_model_weights = get_weights_df(lm, x_train, 'Linear_Model_Weight')
linear_model_weights

Features  Linear_Model_Weight
0          RH_2            -0.456698
1         T_out            -0.321860
2            T2            -0.236178
3            T9            -0.189941
4          RH_8            -0.157595
5        RH_out            -0.077671
6          RH_7            -0.044614
7          RH_9            -0.039800
8            T5            -0.015657
9            T1            -0.003281
10          rv2             0.000770
11          rv1             0.000770
12  Press_mm_hg             0.006839
13           T7             0.010319
14   Visibility             0.012307
15         RH_5             0.016006
16         RH_4             0.026386
17           T4             0.028981
18    Windspeed             0.029183
19         RH_6             0.038049
20         RH_3             0.096048
21           T8             0.101995
22    Tdewpoint             0.117758
23           T6             0.236425
24           T3             0.290627
25         RH_1             0.553547

In [67]:
from sklearn.linear_model import Ridge
ridge_reg = Ridge(alpha=0.4)
ridge_reg.fit(x_train, y_train)
ridge_predict=ridge_reg.predict(X_test)

In [68]:
RMSE = np.sqrt(metrics.mean_squared_error(y_test,ridge_predict))
round(RMSE, 3)

0.088

In [65]:
from sklearn.linear_model import Lasso
lasso_reg = Lasso(alpha=0.001)
lasso_reg.fit(x_train, y_train)
lasso_predict = lasso_reg.predict(X_test)
lasso_predict

array([0.07370267, 0.08143458, 0.07716072, ..., 0.07792848, 0.09034412,
       0.08359255])

In [64]:
def get_weights_df(lm, feat, col_name):
  weights = pd.Series(lm.coef_, feat.columns).sort_values()
  weights_df = pd.DataFrame(weights).reset_index()
  weights_df.columns = ['Features', col_name]
  weights_df[col_name].round(3)
  return weights_df

lasso_weights_df = get_weights_df(lasso_reg, x_train, 'Lasso_weight')
lasso_weights_df

Features  Lasso_weight
0        RH_out     -0.049557
1          RH_8     -0.000110
2            T1      0.000000
3     Tdewpoint      0.000000
4    Visibility      0.000000
5   Press_mm_hg     -0.000000
6         T_out      0.000000
7          RH_9     -0.000000
8            T9     -0.000000
9            T8      0.000000
10         RH_7     -0.000000
11          rv1     -0.000000
12           T7     -0.000000
13           T6      0.000000
14         RH_5      0.000000
15           T5     -0.000000
16         RH_4      0.000000
17           T4     -0.000000
18         RH_3      0.000000
19           T3      0.000000
20         RH_2     -0.000000
21           T2      0.000000
22         RH_6     -0.000000
23          rv2     -0.000000
24    Windspeed      0.002912
25         RH_1      0.017880

In [66]:
RMSE = np.sqrt(metrics.mean_squared_error(y_test,lasso_predict))
round(RMSE, 3)

0.094